create table if not exists public.user_badges (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  badge_key text not null check (
    badge_key in (
      'volltreffer',
      'scharfschuetze',
      'heisse-serie',
      'dauerbrenner',
      'stammkurve',
      'leader',
      'perfekter-spieltag',
      'saisonfighter'
    )
  ),
  unlocked_at timestamptz not null default now(),
  unique (user_id, badge_key)
);

alter table public.user_badges enable row level security;

revoke all on table public.user_badges from anon;
revoke all on table public.user_badges from authenticated;
grant select on table public.user_badges to authenticated;

create policy "Users can view their own badges"
on public.user_badges
for select
to authenticated
using ((select auth.uid()) = user_id);
