create index if not exists tips_match_id_idx on public.tips(match_id);
create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions(user_id);

create table if not exists public.admin_login_attempts (
  id bigint generated by default as identity primary key,
  identifier_hash text not null,
  success boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.admin_login_attempts enable row level security;

drop policy if exists "Kein direkter Client-Zugriff auf Admin-Login-Versuche" on public.admin_login_attempts;
create policy "Kein direkter Client-Zugriff auf Admin-Login-Versuche"
on public.admin_login_attempts
for all
to anon, authenticated
using (false)
with check (false);

create index if not exists admin_login_attempts_identifier_created_idx
on public.admin_login_attempts(identifier_hash, created_at desc);

create index if not exists admin_login_attempts_created_idx
on public.admin_login_attempts(created_at);

drop policy if exists "Eigene oder gestartete Tipps lesen" on public.tips;
create policy "Eigene oder gestartete Tipps lesen"
on public.tips
for select
to authenticated
using (
  (select auth.uid()) = user_id
  or exists (
    select 1
    from public.matches
    where matches.id = tips.match_id
      and now() >= matches.kickoff
  )
);

drop policy if exists "Eigene Tipps nur vor Anpfiff erstellen" on public.tips;
create policy "Eigene Tipps nur vor Anpfiff erstellen"
on public.tips
for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.matches
    where matches.id = tips.match_id
      and now() < matches.kickoff
      and coalesce(matches.live_status, '') <> 'PST'
      and matches.finished = false
  )
);

drop policy if exists "Eigene Tipps nur vor Anpfiff ändern" on public.tips;
create policy "Eigene Tipps nur vor Anpfiff ändern"
on public.tips
for update
to authenticated
using (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.matches
    where matches.id = tips.match_id
      and now() < matches.kickoff
      and coalesce(matches.live_status, '') <> 'PST'
      and matches.finished = false
  )
)
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.matches
    where matches.id = tips.match_id
      and now() < matches.kickoff
      and coalesce(matches.live_status, '') <> 'PST'
      and matches.finished = false
  )
);

drop policy if exists "push subscriptions select own" on public.push_subscriptions;
create policy "push subscriptions select own"
on public.push_subscriptions
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "push subscriptions insert own" on public.push_subscriptions;
create policy "push subscriptions insert own"
on public.push_subscriptions
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "push subscriptions update own" on public.push_subscriptions;
create policy "push subscriptions update own"
on public.push_subscriptions
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "push subscriptions delete own" on public.push_subscriptions;
create policy "push subscriptions delete own"
on public.push_subscriptions
for delete
to authenticated
using ((select auth.uid()) = user_id);
